Document: nr-deckbuilder
Title: Debian nr-deckbuilder Manual
Author: <insert document author here>
Abstract: This manual describes what nr-deckbuilder is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nr-deckbuilder/nr-deckbuilder.sgml.gz

Format: postscript
Files: /usr/share/doc/nr-deckbuilder/nr-deckbuilder.ps.gz

Format: text
Files: /usr/share/doc/nr-deckbuilder/nr-deckbuilder.text.gz

Format: HTML
Index: /usr/share/doc/nr-deckbuilder/html/index.html
Files: /usr/share/doc/nr-deckbuilder/html/*.html
